### ISSUE TITLE
Doesn't build with iOS Cordova 4.0.1

### ISSUE THREAD

**Issue by benmcmaster** [photokandyStudios/PKVideoThumbnail#6]
Love this plugin, but it's not compiling with Phonegap Build cli-6.0.0. That uses iOS 4.0.1. Any ideas?

The following build commands failed:
	CompileC build/VimifyDev.build/Release-iphoneos/VimifyDev.build/Objects-normal/armv7/PKVideoThumbnail.o VimifyDev/Plugins/com.photokandy.videothumbnail/PKVideoThumbnail.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by kerrishotts** [comment]
Hi @benmcmaster - I'm working on a new version that will support 4.0.1. See the 2.x branch. I've got the iOS code mostly where I want it, and will be working on Android shortly. You're welcome to try it, although there is a currently a slight breaking change because 2.x introduces various option settings.

I'm hoping to have the release finalized in a few days, if that helps any.

**Comment by robincrorie** [comment]
@kerrishotts: firstly, great work on this plugin. Just wondering if there was any update on the v2.x? Eagerly awaiting the 4.0.1 support! :)

**Comment by kerrishotts** [comment]
2.x just released; let me know if any of you have problems!

**Comment by benmcmaster** [comment]
Thank you! I am finally getting around to testing it out. I will let you know how it goes.
